baseurl = "/"
enableGitInfo = true
enableRobotsTXT = true
editor = "code"
languageCode = "en-US"
language = "en"
title = "Tony Burns"
theme = "wilson"

disablePathToLower = true

[permalinks]
  articles = "articles/:slug/"
  notes = "notes/:slug/"
  photos = "photos/:slug/"

[params]
  mainSections = ["articles", "notes", "photos"]
  
  [[params.links]]
    rel = "authorization_endpoint"
    href = "https://singulus.dev/indieauth/authorize"

  [[params.links]]
    rel = "token_endpoint"
    href = "https://singulus.dev/indieauth/token"

  [[params.links]]
    rel = "micropub"
    href = "https://singulus.dev/micropub"

  [[params.links]]
    rel = "webmention"
    href = "https://singulus.dev/webmentions"
